project:
  type: website

website:
  title: "Advent of Code"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: year_2021/index.qmd
      - href: year_2022/index.qmd
      - href: year_2023/index.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
