---
title: "2021 - Day 11"
format:
  html:
    code-fold: show
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#AB63BD"
---

## Set-Up

```{r setup}
octopi <- read.fwf("input.txt", widths = rep(1, 10))
octopi <- as.matrix(octopi)
str(octopi)
```

## Part 1

```{r part_1}
countNFlashes <- function(octopi, n = 100, i = 1, flashes = 0) {
  octopi <- octopi + 1

  new_flashing_octopi <- flashing_octopi <- octopi > 9
  while (any(new_flashing_octopi)) {
    new_locations <- which(new_flashing_octopi, arr.ind = TRUE)
    updating_octopi <- apply(new_locations, 1, findSurroundingOctopi, simplify = FALSE)

    for (j in seq_along(updating_octopi)) {
      octopi[updating_octopi[[j]]] <- octopi[updating_octopi[[j]]] + 1
    }

    new_flashing_octopi <- octopi > 9 & !flashing_octopi
    flashing_octopi <- octopi > 9
  }

  flashes <- flashes + sum(octopi > 9)
  octopi[flashing_octopi] <- 0

  if (i == n) {
    flashes
  } else {
    countNFlashes(octopi, n, i + 1, flashes)
  }
}

findSurroundingOctopi <- function(x) {
  # Getting box of locations
  boxLocations <- \(x) max(1, x - 1):min(10, x + 1)
  rows <- boxLocations(x[1])
  cols <- boxLocations(x[2])
  cbind(row = rep(rows, times = length(cols)), col = rep(cols, each = length(rows)))
}

countNFlashes(octopi)
```

## Part 2

```{r part_2}
findAllFlashes <- function(octopi, i = 1) {
  octopi <- octopi + 1

  new_flashing_octopi <- flashing_octopi <- octopi > 9
  while (any(new_flashing_octopi)) {
    new_locations <- which(new_flashing_octopi, arr.ind = TRUE)
    updating_octopi <- apply(new_locations, 1, findSurroundingOctopi, simplify = FALSE)

    for (j in seq_along(updating_octopi)) {
      octopi[updating_octopi[[j]]] <- octopi[updating_octopi[[j]]] + 1
    }

    new_flashing_octopi <- octopi > 9 & !flashing_octopi
    flashing_octopi <- octopi > 9
  }

  octopi[flashing_octopi] <- 0

  if (all(flashing_octopi)) {
    i
  } else {
    findAllFlashes(octopi, i + 1)
  }
}

findAllFlashes(octopi)
```
