---
title: "2021 - Day 21"
format:
  html:
    code-fold: show
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#AB63BD"
---

## Set-Up

```{r setup}
start_positions <- read.delim(
  "input.txt", header = FALSE, sep = " ",
  col.names = c("x", "player", "y", "z", "start")
)
str(start_positions)
```

## Part 1

```{r part_1}
addScore <- function(p1, p2, s1 = 0, s2 = 0, turn = 1, i = 1, cnt = 3) {
  code <- "p1 <- (p1 + sum(i:(i + 2) %% 10)) %% 10; if (p1 == 0) p1 <- 10; s1 <- s1 + p1"
  if (turn == 2) code <- gsub("(p|s)1", "\\12", code)
  eval(parse(text = code))

  if (s1 >= 1000 || s2 >= 1000) {
    c(s1, s2)[c(s1, s2) < 1000] * cnt
  } else {
    addScore(p1, p2, s1, s2, 3 - turn, (i + 3) %/% 101 + (i + 3) %% 101, cnt + 3)
  }
}

addScore(start_positions$start[1], start_positions$start[2])
```

## Part 2

```{r part_2, eval=FALSE}
pot_scores <- expand.grid(1:3, 1:3, 1:3)
pot_values <- c(0, 0, table(rowSums(pot_scores)))
cache <- list()

addScore2 <- function(p1, p2, s1 = 0, s2 = 0, turn = 1, cnt = 1) {
  cache_name <- paste(p1, p2, s1, s2, turn)
  if (cache_name %in% names(cache)) {
    cache[[cache_name]] * cnt
  } else {
    rowSums(
      sapply(9:3, \(x) {
        if (turn == 1) {
          p1 <- (p1 + x) %% 10; if (p1 == 0) p1 <- 10; s1 <- s1 + p1
        } else {
          p2 <- (p2 + x) %% 10; if (p2 == 0) p2 <- 10; s2 <- s2 + p2
        }

        if (s1 >= 21 || s2 >= 21) {
          cnt * pot_values[[x]] * as.numeric(turn == c(1, 2))
        } else  {
          value <- addScore2(p1, p2, s1, s2, 3 - turn, cnt * pot_values[[x]])
          cache_name <- paste(p1, p2, s1, s2, 3 - turn)
          if (!cache_name %in% names(cache)) {
            cache[[cache_name]] <<- value / cnt / pot_values[[x]]
          }
          value
        }
      })
    )
  }
}

addScore2(8, 2)
```
