---
format:
  html:
    code-fold: show
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#AB63BD"
---

## Set-Up

```{r setup}
commands <- readLines("input.txt")
```

## Part 1

```{r part_1}
sub_commands <- commands
matching_regex <- "\\(\\)|\\[\\]|\\{\\}|<>"

while (any(grepl(matching_regex, sub_commands))) {
  sub_commands <- gsub(matching_regex, "", sub_commands)
}

# First invalid closing bracket
invalid_commands <- substr(gsub("\\(|\\[|\\{|<", "", sub_commands), 1, 1)
invalid_commands <- invalid_commands[invalid_commands != ""]

error_sizes <- c(")" = 3, "]" = 57, "}" = 1197, ">" = 25137)
sum(table(invalid_commands) * error_sizes)
```

## Part 2

```{r part_2}
incomplete_values <- c("(", "[", "{", "<")
incomplete_commands <- grep("\\)|\\}|\\]|>", sub_commands, value = TRUE, invert = TRUE)

incomplete_scores <- sapply(strsplit(incomplete_commands, ""), \(x) {
  scores <- rev(match(x, incomplete_values))
  y <- 0
  for (i in seq_along(scores)) y <- 5 * y + scores[i]
  y
})
median(incomplete_scores)
```
